### ISSUE TITLE
AttributeError: module 'my_interp' has no attribute 'run'

### ISSUE THREAD

**Issue by wjywjy14** [cfzd/Ultra-Fast-Lane-Detection-v2#14]
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    train(net, train_loader, loss_dict, optimizer, scheduler,logger, epoch, metric_dict, cfg.dataset)
  File "train.py", line 17, in train
    for b_idx, data_label in enumerate(progress_bar):
  File "/home/wjy/anaconda3/envs/lane-det/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/wjy/Ultra-Fast-Lane-Detection-V2/data/dali_data.py", line 246, in __next__
    points_row = my_interp.run(points, self.interp_loc_row, 0)
AttributeError: module 'my_interp' has no attribute 'run'

**Comment by cfzd** [comment]
@wjywjy14 
have you successfully installed the CUDA extension?
```
cd my_interp

sh build.sh
# If this fails, you might need to upgrade your GCC to v7.3.0
```

**Comment by wjywjy14** [comment]
我安装的是cuda11.1,请问有影响吗

**Comment by cfzd** [comment]
@wjywjy14 
不好意思，我的意思不是CUDA的版本，而是你安装成功我们这个`my_interp`的CUDA拓展了没有，安装方式就是上面写的`sh build.sh`。

**Comment by wjywjy14** [comment]
安装没有完全成功，有部分报错，是需要gcc7.3.0才能安装成功吗

**Comment by cfzd** [comment]
@wjywjy14 
你可以找一下是报什么错，如果是一些类型转换不对的错的话，可能得需要升级gcc，或者你也可以安装个本地的gcc，临时用一下

**Comment by jd926** [comment]
我查看了gcc的版本
gcc version 9.4.0(Ubuntu 9.4.0-1ubuntu1-20.04.1)

**Comment by cfzd** [comment]
@jd926 
如果出现这个问题，肯定是你编译my_interp的CUDA和你pytorch的CUDA不一样导致的。你的pytorch可能用的是通过conda安装的libcudatoolkit，而你编译my_interp的是你本地的cuda。你可以通过如下方式查看：
- libcudatoolkit: `conda list | grep cuda`
- 本地cuda: `ls -al /usr/local/cuda`
如果他们版本不一致，那么你需要安装一个和pytorch的libcudatoolkit版本一致的本地cuda编译my_interp

**Comment by jd926** [comment]
> @jd926 如果出现这个问题，肯定是你编译my_interp的CUDA和你pytorch的CUDA不一样导致的。你的pytorch可能用的是通过conda安装的libcudatoolkit，而你编译my_interp的是你本地的cuda。你可以通过如下方式查看：
> 
> * libcudatoolkit: `conda list | grep cuda`
> * 本地cuda: `ls -al /usr/local/cuda`
>   如果他们版本不一致，那么你需要安装一个和pytorch的libcudatoolkit版本一致的本地cuda编译my_inter
好的，非常感谢您！
