### ISSUE TITLE
Can't find: 'list/test_split/test0_normal.txt'

### ISSUE THREAD

**Issue by MaxenceRemy** [cfzd/Ultra-Fast-Lane-Detection-v2#147]
Hello erveryone,

I installed everything properly on Ubuntu and managed to get the Tensorrt inference work, but because the results are not very good with it, I wanted to try the demo.py.

But when I run it, I get this error, and I didn't find a person with the same issue here : 

Traceback (most recent call last):
  File "demo.py", line 94, in <module>
    datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms, crop_size = cfg.train_height) for split in splits]
  File "demo.py", line 94, in <listcomp>
    datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms, crop_size = cfg.train_height) for split in splits]
  File "/home/ubuntu/Ultra-Fast-Lane-Detection-V2/data/dataset.py", line 20, in __init__
    with open(list_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'list/test_split/test0_normal.txt'(my_venv)

How can I solve that problem ?

**Comment by Maynafiesta** [comment]
having the same issue, checked the code but didnt find a way, any suggestion?

**Comment by umie0128** [comment]
![image](https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2/assets/49420977/b1d8780c-0067-49b3-89cf-6e938b7bb650)
check the file root
