### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './tmp/txt/out0_curve.txt'

### ISSUE THREAD

**Issue by pwshen** [cfzd/Ultra-Fast-Lane-Detection-v2#15]
[](url)i got FileNotFoundError when i try to evaluate the pretrained model on Curvelanes

i run the test.py with following command
`python test.py configs/curvelanes_res18.py --test_model ./work_dirs/curvelanes_res18.pth --test_work_dir ./tmp`

result:

Traceback (most recent call last):
  File "test.py", line 36, in <module>
    eval_lane(net, cfg)
  File "/home/powei/Ultra-Fast-Lane-Detection-v2-master/evaluation/eval_wrapper.py", line 853, in eval_lane
    res = call_curvelane_eval(cfg.data_root, 'curvelanes_eval_tmp', cfg.test_work_dir)
  File "/home/powei/Ultra-Fast-Lane-Detection-v2-master/evaluation/eval_wrapper.py", line 1057, in call_curvelane_eval
    res_all['res_curve'] = read_helper(out0)
  File "/home/powei/Ultra-Fast-Lane-Detection-v2-master/evaluation/eval_wrapper.py", line 960, in read_helper
    lines = open(path, 'r').readlines()[1:]
FileNotFoundError: [Errno 2] No such file or directory: './tmp/txt/out0_curve.txt'

i have successfully built culane_evaluator

`Scanning dependencies of target culane_evaluator
[ 20%] Building CXX object CMakeFiles/culane_evaluator.dir/src/counter.cpp.o
[ 40%] Building CXX object CMakeFiles/culane_evaluator.dir/src/evaluate.cpp.o
[ 60%] Building CXX object CMakeFiles/culane_evaluator.dir/src/lane_compare.cpp.o
[ 80%] Building CXX object CMakeFiles/culane_evaluator.dir/src/spline.cpp.o
[100%] Linking CXX executable culane_evaluator
[100%] Built target culane_evaluator
`

**Comment by pwshen** [comment]
the issue is solved 
the problem is opencv path
`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`
