### ISSUE TITLE
curvelane转换为tusimple格式和tusimple数据集一起训练

### ISSUE THREAD

**Issue by wjywjy14** [cfzd/Ultra-Fast-Lane-Detection-v2#17]
博主你好，我将curvelane数据集转换为tusimple格式后与tusimple放在一起，使用convert_tusimple.py进行分割，出现以下错误：

VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  lanes = [np.array(l['lanes']) for l in label_json_all]  # 车道
Traceback (most recent call last):
  File "/home/wjy/Ultra-Fast-Lane-Detection-V2/scripts/convert_tusimple.py", line 202, in <module>
    'label_data_driver_161_90frame.json', 'label_data_driver_182_30frame.json'])
  File "/home/wjy/Ultra-Fast-Lane-Detection-V2/scripts/convert_tusimple.py", line 63, in get_tusimple_list
    line_txt_tmp = [None] * (len(h_samples[i][valid]) + len(lanes[i][j][valid]))
TypeError: object of type 'int' has no len()

**Comment by cfzd** [comment]
@wjywjy14 
因为我不知道你是怎么把curvelane转换为tusimple的，所以我没法知道这个错误的根源。但是似乎错误提示是`len(h_samples[i][valid]`或者`len(lanes[i][j][valid])`里的变量是个int，所以你不能使用`len`函数
