### ISSUE TITLE
运行sh build.sh时获取不到CUDA_HOME的环境变量信息

### ISSUE THREAD

**Issue by yxs87** [cfzd/Ultra-Fast-Lane-Detection-v2#183]
(lane-det) yxs@yxs-System-Product-Name:~/object/lane/my_interp$ 
sh build.sh
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    CUDAExtension('my_interp', [
  File "/home/yxs/anaconda3/envs/lane-det/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1077, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/yxs/anaconda3/envs/lane-det/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1204, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/yxs/anaconda3/envs/lane-det/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2419, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by 2155170035** [comment]
请问是怎么解决的
