### ISSUE TITLE
Version of Python and question about the system

### ISSUE THREAD

**Issue by Lyfun222** [cfzd/Ultra-Fast-Lane-Detection-v2#185]
There is an conflict that DALI-cuda110 needs the version 3.8 of Python. But in the INSTALL document, you said we need to install python 3.7. Is it an conflict or problem?

Is it avaliable to run the code in Windows System? Or it can only be run in the Linux System?

**Comment by Lyfun222** [comment]
@cfzd
I downloaded Pycharm and built WSL2 and other environment by following INSTALL document. 
But there are some problems that I can't run this program in the Pycharm. Could you tell me how to solve these?

Traceback (most recent call last):
  File "D:\Ultra-Fast-Lane-Detection-v2-master\demo.py", line 4, in <module>
    from utils.common import merge_config, get_model
  File "D:\Ultra-Fast-Lane-Detection-v2-master\utils\common.py", line 2, in <module>
    from data.dali_data import TrainCollect
  File "D:\Ultra-Fast-Lane-Detection-v2-master\data\dali_data.py", line 4, in <module>
    from nvidia.dali.pipeline import Pipeline
ModuleNotFoundError: No module named 'nvidia'
