### ISSUE TITLE
Curvelanes validation error while training

### ISSUE THREAD

**Issue by supportman007** [cfzd/Ultra-Fast-Lane-Detection-v2#195]
Im trying to train a model with curvelanes dataset. Im getting an error like this:

``100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2500/2500 [10:21<00:00,  4.02it/s]
./evaluate -s -a /home/kutsal/Desktop/efekan/Curvelanes/ -d /home/kutsal/Desktop/20241209_105109_lr_5e-02_b_4/curvelanes_eval_tmp/ -i /home/kutsal/Desktop/efekan/Curvelanes/ -l /home/kutsal/Desktop/efekan/Curvelanes/valid/valid_for_culane_style.txt -w 5 -t 0.5 -c 224 -r 224 -f 1 -o /home/kutsal/Desktop/20241209_105109_lr_5e-02_b_4/txt/out0_curve.txt -x 0.0875 -y 0.15555555555555556
sh: 1: ./evaluation/culane/evaluate: not found
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    res = eval_lane(net, cfg, ep = epoch, logger = logger)
  File "/home/kutsal/Desktop/efekan/Ultra-Fast-Lane-Detection-V2/evaluation/eval_wrapper.py", line 853, in eval_lane
    res = call_curvelane_eval(cfg.data_root, 'curvelanes_eval_tmp', cfg.test_work_dir)
  File "/home/kutsal/Desktop/efekan/Ultra-Fast-Lane-Detection-V2/evaluation/eval_wrapper.py", line 1057, in call_curvelane_eval
    res_all['res_curve'] = read_helper(out0)
  File "/home/kutsal/Desktop/efekan/Ultra-Fast-Lane-Detection-V2/evaluation/eval_wrapper.py", line 960, in read_helper
    lines = open(path, 'r').readlines()[1:]
FileNotFoundError: [Errno 2] No such file or directory: '/home/kutsal/Desktop/20241209_105109_lr_5e-02_b_4/txt/out0_curve.txt'

**Comment by supportman007** [comment]
I build the evaluation tool of CULane with option 2 in install.md and it worked.
