### ISSUE TITLE
python train.py configs/culane_res18.py     FileNotFoundError: [Errno 2] No such file or directory: 'out_culane/20220901_204530_lr_5e-02_b_32/txt/out0_normal.txt'

### ISSUE THREAD

**Issue by Aruen24** [cfzd/Ultra-Fast-Lane-Detection-v2#29]
cached data loaded
2778
100%|██████████████████████████████| 2778/2778 [56:40<00:00,  1.22s/it, col_top1=0.039, col_top2=0.107, col_top3=0.146, ext_col=0.946, ext_row=0.936, loss=5.363, top1=0.067, top2=0.174, top3=0.251]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4335/4335 [39:22<00:00,  1.83it/s]
sh: 1: ./evaluation/culane/evaluate: Permission denied
sh: 1: ./evaluation/culane/evaluate: Permission denied
sh: 1: ./evaluation/culane/evaluate: Permission denied
sh: 1: ./evaluation/culane/evaluate: Permission denied
sh: 1: ./evaluation/culane/evaluate: Permission denied
sh: 1: ./evaluation/culane/evaluate: Permission denied
sh: 1: ./evaluation/culane/evaluate: Permission denied
sh: 1: ./evaluation/culane/evaluate: Permission denied
sh: 1: ./evaluation/culane/evaluate: Permission denied
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    res = eval_lane(net, cfg, ep = epoch, logger = logger)
  File "/home/disk01/wyw/Ultra-Fast-Lane-Detection-v2/evaluation/eval_wrapper.py", line 899, in eval_lane
    res = call_culane_eval(cfg.data_root, 'culane_eval_tmp', cfg.test_work_dir)
  File "/home/disk01/wyw/Ultra-Fast-Lane-Detection-v2/evaluation/eval_wrapper.py", line 1022, in call_culane_eval
    res_all['res_normal'] = read_helper(out0)
  File "/home/disk01/wyw/Ultra-Fast-Lane-Detection-v2/evaluation/eval_wrapper.py", line 960, in read_helper
    lines = open(path, 'r').readlines()[1:]
FileNotFoundError: [Errno 2] No such file or directory: 'out_culane/20220901_204530_lr_5e-02_b_32/txt/out0_normal.txt'

**Comment by cfzd** [comment]
@Aruen24 
Please install CULane evaluation tools as the `install.md` says.
