### ISSUE TITLE
Some problem about my_interp in training

### ISSUE THREAD

**Issue by Nitrogen216** [cfzd/Ultra-Fast-Lane-Detection-v2#32]
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from utils.common import calc_loss, get_model, get_train_loader, inference, merge_config, save_model, cp_projects
  File "/home/ubuntu/user_space/Ultra-Fast-Lane-Detection-V2/utils/common.py", line 2, in <module>
    from data.dali_data import TrainCollect
  File "/home/ubuntu/user_space/Ultra-Fast-Lane-Detection-V2/data/dali_data.py", line 11, in <module>
    import my_interp
**ImportError: /home/ubuntu/miniconda3/lib/python3.7/site-packages/my_interp-0.0.0-py3.7-linux-x86_64.egg/my_interp.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE**

and my gcc version is updated to 7.3.0, so I do not aware of the reason why this problem arise. Tks!

**Comment by Nitrogen216** [comment]
I have solved this problem. The reason why this problem arise is I have compiled my_interp with CUDA10.1 first, I just delete the old version my_interp and then compile it with CUDA10.2 again. It works.

**Comment by jd926** [comment]
> I have solved this problem. The reason why this problem arise is I have compiled my_interp with CUDA10.1 first, I just delete the old version my_interp and then compile it with CUDA10.2 again. It works.

I'm guessing we have the problem. I don't know how to solve it. 
AttributeError: module 'my_interp' has no attribute 'run'
then I  sh build.sh, The following error occurred

The detected CUDA version (10.1) mismatches the version that was used to compile
Pytorch (11.3). Please make sure to use the same CUDA versions.

my gcc version is updated to 9.4.0

Thank you!

**Comment by cfzd** [comment]
@jd926 
I have replied in #14
