### ISSUE TITLE
How to disable CUDA?

### ISSUE THREAD

**Issue by konrin** [cfzd/Ultra-Fast-Lane-Detection-v2#59]
I want to run this model on mac m1, but I'm facing a lack of CUDA

**Comment by cfzd** [comment]
@konrin 

If you want to run this model for inference or evaluation, I think it is ok. You just need to cancel all of the `.cuda()` calls in the pipeline.

But if you want to train this model on m1, I think it might be hard since the key component `my_interp` lib is written in CUDA, which is used for data loading in training. And I think using python or pytorch to implement this lib is also difficult, because the training speed would be significantly slow.

**Comment by konrin** [comment]
Thanks for your answer!
Yes, I just wanted to evaluate the performance of the model on the trained scales, but I ran into the problem of the nvidia package requirement

```
python demo.py configs/culane_res34.py --test_model /Users/konrin/projects/Ultra-Fast-Lane-Detection-v2/culane_res34.pth                      

Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from utils.common import merge_config, get_model
  File "~/Ultra-Fast-Lane-Detection-v2/utils/common.py", line 2, in <module>
    from data.dali_data import TrainCollect
  File "~/Ultra-Fast-Lane-Detection-v2/data/dali_data.py", line 4, in <module>
    from nvidia.dali.pipeline import Pipeline
ModuleNotFoundError: No module named 'nvidia'
```

**Comment by cfzd** [comment]
@konrin 
I think you can temporally comment out the `nvidia` line, which is from nvidia DALI.
