### ISSUE TITLE
sh build.sh 报错问题

### ISSUE THREAD

**Issue by NeruQ** [cfzd/Ultra-Fast-Lane-Detection-v2#82]
我建了个全新的conda环境，按照您的install指南安装了
```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
```
我的gcc 和 g++版本为7.5.0
报错为：
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.4'
running install
/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing my_interp.egg-info/PKG-INFO
writing dependency_links to my_interp.egg-info/dependency_links.txt
writing top-level names to my_interp.egg-info/top_level.txt
/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'my_interp.egg-info/SOURCES.txt'
writing manifest file 'my_interp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 382, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/qianyinfei/anaconda3/envs/lane-det/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
请问问题出在哪里呢？

**Comment by cfzd** [comment]
@NeruQ 
这个有可能的问题是现在新的pytorch版本已经不支持cuda10.2了，或许可以根据这个重装一下环境：
```
conda install pytorch torchvision pytorch-cuda=11.6 -c pytorch -c nvidia
```
