### ISSUE TITLE
No module named 'nvidia.dali.pipeline'

### ISSUE THREAD

**Issue by the-cat-crying** [cfzd/Ultra-Fast-Lane-Detection-v2#84]
File "train.py", line 8, in <module>
    from utils.common import calc_loss, get_model, get_train_loader, inference, merge_config, save_model, cp_projects
  File "/home/zp/work/Ultra-Fast-Lane-Detection-V2/utils/common.py", line 2, in <module>
    from data.dali_data import TrainCollect
  File "/home/zp/work/Ultra-Fast-Lane-Detection-V2/data/dali_data.py", line 4, in <module>
    from nvidia.dali.pipeline import Pipeline
ModuleNotFoundError: No module named 'nvidia.dali.pipeline'

ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.21.5           py37ha15fc14_3  
nvidia-dali-cuda110       1.21.0                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
onnx                      1.12.0                   pypi_0    pypi
onnxoptimizer             0.3.1                    pypi_0    pypi
onnxruntime-gpu           1.12.1                   pypi_0    pypi
opencv-contrib-python     4.6.0.66                 pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.6.0.66                 pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0  
packaging                 21.3                     pypi_0    pypi
pathspec                  0.10.1                   pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.2.2           py37h06a4308_0  
protobuf                  3.19.6                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.7.13               haa1d7c7_1  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.7.0           py3.7_cuda11.0.221_cudnn8.0.3_0    pytorch
readline                  8.1.2                h7f8727e_1  
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                63.4.1           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.39.3               h5082296_0  
sympy                     1.10.1                   pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torch                     1.12.1+cu113             pypi_0    pypi
torchaudio                0.12.1                   pypi_0    pypi
torchvision               0.13.1+cu113             pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
typing_extensions         4.4.0            py37h06a4308_0  
ujson                     5.5.0                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.6                h5eee18b_0  
zipp                      3.9.0                    pypi_0    pypi
zlib                      1.2.12               h5eee18b_3  
zstd                      1.5.2                ha4553b6_0

**Comment by luca-demartino** [comment]
I have the same problem, it seems that DALI is only available for Linux and not for Windows. I haven't managed to solve it yet unfortunately

**Comment by FriendChi** [comment]
you should download dali

**Comment by Shivanshu8211** [comment]
I think I don't have a dedicated Nvidia GPU, so I can't download it. See if there is any other issue

PS D:\C-drive\LastMile\Sprint_1\lane-detection-enet-pytorch-lanedetection_enet-v2\Ultra-Fast-Lane-Detection-v2>
 pip install nvidia-pyindex
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: nvidia-pyindex in c:\users\arisa\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.0.9)
PS D:\C-drive\LastMile\Sprint_1\lane-detection-enet-pytorch-lanedetection_enet-v2\Ultra-Fast-Lane-Detection-v2>
 pip install nvidia-dali    
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting nvidia-dali
  Downloading nvidia-dali-0.0.1.dev5.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\arisa\AppData\Local\Temp\pip-install-lh13dpx_\nvidia-dali_567e31fbe6ca4b1c982f8417d91378fa\setup.py", line 150, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install nvidia-dali
      ```

      Please refer to NVIDIA DALI installation guide for instructions:
      https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html
      ###########################################################################################
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by FriendChi** [comment]
The Dali seems to only have a Linux version available

**Comment by FriendChi** [comment]
The Dali library seems to only have a Linux version available
