### ISSUE TITLE
my_interp.cpython-37m-x86_64-linux-gnu.so: undefined symbol: 

### ISSUE THREAD

**Issue by the-cat-crying** [cfzd/Ultra-Fast-Lane-Detection-v2#85]
(lanedetv2) [zp@localhost Ultra-Fast-Lane-Detection-V2]$ python train.py configs/tusimple_res18.py --log_path ./
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from utils.common import calc_loss, get_model, get_train_loader, inference, merge_config, save_model, cp_projects
  File "/home/zp/work/Ultra-Fast-Lane-Detection-V2/utils/common.py", line 2, in <module>
    from data.dali_data import TrainCollect
  File "/home/zp/work/Ultra-Fast-Lane-Detection-V2/data/dali_data.py", line 11, in <module>
    import my_interp
ImportError: /home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages/my_interp-0.0.0-py3.7-linux-x86_64.egg/my_interp.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE

**Comment by cfzd** [comment]
Have you installed `myinterp` as the `INSTALL.md` says？

**Comment by the-cat-crying** [comment]
(lanedetv2) [zp@localhost my_interp]$ sh build.sh 
running install
/home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing my_interp.egg-info/PKG-INFO
writing dependency_links to my_interp.egg-info/dependency_links.txt
writing top-level names to my_interp.egg-info/top_level.txt
/home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'my_interp.egg-info/SOURCES.txt'
writing manifest file 'my_interp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-cpython-37/my_interp.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for my_interp.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/my_interp.py to my_interp.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying my_interp.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying my_interp.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying my_interp.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying my_interp.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.my_interp.cpython-37: module references __file__
creating 'dist/my_interp-0.0.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing my_interp-0.0.0-py3.7-linux-x86_64.egg
removing '/home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages/my_interp-0.0.0-py3.7-linux-x86_64.egg' (and everything under it)
creating /home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages/my_interp-0.0.0-py3.7-linux-x86_64.egg
Extracting my_interp-0.0.0-py3.7-linux-x86_64.egg to /home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages
my-interp 0.0.0 is already the active version in easy-install.pth

Installed /home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages/my_interp-0.0.0-py3.7-linux-x86_64.egg
Processing dependencies for my-interp==0.0.0
Finished processing dependencies for my-interp==0.0.0

**Comment by the-cat-crying** [comment]
(lanedetv2) [zp@localhost Ultra-Fast-Lane-Detection-V2]$ python train.py configs/tusimple_res18.py --log_path ./
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from utils.common import calc_loss, get_model, get_train_loader, inference, merge_config, save_model, cp_projects
  File "/home/zp/work/Ultra-Fast-Lane-Detection-V2/utils/common.py", line 2, in <module>
    from data.dali_data import TrainCollect
  File "/home/zp/work/Ultra-Fast-Lane-Detection-V2/data/dali_data.py", line 11, in <module>
    import my_interp
ImportError: /home/zp/.conda/envs/lanedetv2/lib/python3.7/site-packages/my_interp-0.0.0-py3.7-linux-x86_64.egg/my_interp.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE
(lanedetv2) [zp@localhost Ultra-Fast-Lane-Detection-V2]$

**Comment by cfzd** [comment]
@the-cat-crying 
I think it might be a problem of cuda version mismatch. The cuda used for build `my_interp` is called by `nvcc`, which you can find by:
```
nvcc -V
```
This is the local cuda.


However, the cuda that pytorch uses might comes from conda, which you can find by:
```
conda list | grep cuda
```
This is the conda cuda.

You can compare the information to find the problem.

**Comment by the-cat-crying** [comment]
Thanks！

but,, I installed it according to your documentation, so how do I replace it with the local cuda path?

**Comment by the-cat-crying** [comment]
@cfzd

**Comment by the-cat-crying** [comment]
@cfzd

The environment issue seems to work, but this error is reported during training

 (lane-det) root@DESKTOP-K0HD6EP:~/work/ultra-fast-lane-detection-V2# python train.py configs/tusimple_res18.py --log_path ./tmp/
merge  log_path  config
rm: cannot remove '.work_dir_tmp_file.txt': No such file or directory
[2023/02/12 10:19:26] start training...
Config (path: configs/tusimple_res18.py): {'dataset': 'Tusimple', 'data_root': '/root/work/ultra-fast-lane-detection-V2/dataset', 'epoch': 100, 'batch_size': 16, 'optimizer': 'SGD', 'learning_rate': 0.05, 'weight_decay': 0.0001, 'momentum': 0.9, 'scheduler': 'multi', 'steps': [50, 75], 'gamma': 0.1, 'warmup': 'linear', 'warmup_iters': 100, 'backbone': '18', 'griding_num': 100, 'use_aux': False, 'sim_loss_w': 0.0, 'shp_loss_w': 0.0, 'note': '', 'log_path': './tmp/', 'finetune': None, 'resume': None, 'test_model': '', 'test_work_dir': './tmp/20230212_101926_lr_5e-02_b_16', 'num_lanes': 4, 'var_loss_power': 2.0, 'auto_backup': True, 'num_row': 56, 'num_col': 41, 'train_width': 800, 'train_height': 320, 'num_cell_row': 100, 'num_cell_col': 100, 'mean_loss_w': 0.05, 'fc_norm': False, 'soft_loss': True, 'cls_loss_col_w': 1.0, 'cls_ext_col_w': 1.0, 'mean_loss_col_w': 0.05, 'eval_mode': 'normal', 'crop_ratio': 0.8, 'row_anchor': array([0.22222222, 0.23611111, 0.25      , 0.26388889, 0.27777778,
       0.29166667, 0.30555556, 0.31944444, 0.33333333, 0.34722222,
       0.36111111, 0.375     , 0.38888889, 0.40277778, 0.41666667,
       0.43055556, 0.44444444, 0.45833333, 0.47222222, 0.48611111,
       0.5       , 0.51388889, 0.52777778, 0.54166667, 0.55555556,
       0.56944444, 0.58333333, 0.59722222, 0.61111111, 0.625     ,
       0.63888889, 0.65277778, 0.66666667, 0.68055556, 0.69444444,
       0.70833333, 0.72222222, 0.73611111, 0.75      , 0.76388889,
       0.77777778, 0.79166667, 0.80555556, 0.81944444, 0.83333333,
       0.84722222, 0.86111111, 0.875     , 0.88888889, 0.90277778,
       0.91666667, 0.93055556, 0.94444444, 0.95833333, 0.97222222,
       0.98611111]), 'col_anchor': array([0.   , 0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ,
       0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  , 0.425,
       0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  , 0.625, 0.65 ,
       0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  , 0.825, 0.85 , 0.875,
       0.9  , 0.925, 0.95 , 0.975, 1.   ]), 'distributed': False}
loading cached data
cached data loaded
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    train_loader = get_train_loader(cfg)
  File "/root/work/ultra-fast-lane-detection-V2/utils/common.py", line 189, in get_train_loader
    cfg.row_anchor, cfg.col_anchor, cfg.train_width, cfg.train_height, cfg.num_cell_row, cfg.num_cell_col, cfg.dataset, cfg.crop_ratio)
  File "/root/work/ultra-fast-lane-detection-V2/data/dali_data.py", line 229, in __init__
    self.pii = DALIGenericIterator(pipe, output_map = ['images', 'seg_images', 'points'], last_batch_padded=True, last_batch_policy=LastBatchPolicy.PARTIAL)
  File "/home/miniconda3/envs/lane-det/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 189, in __init__
    prepare_first_batch=prepare_first_batch)
  File "/home/miniconda3/envs/lane-det/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 199, in __init__
    p.build()
  File "/home/miniconda3/envs/lane-det/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 861, in build
    self._pipe.Build(self._generate_build_args())
RuntimeError: Critical error when building pipeline:
Error when constructing operator: decoders__Image, instance name: "__Image_4", encountered:
Error in thread 0: nvml error (3): The nvml requested operation is not available on target device
Current pipeline object is no longer valid.
(lane-det) root@DESKTOP-K0HD6EP:~/work/ultra-fast-lane-detection-V2#

**Comment by the-cat-crying** [comment]
Thanks！

Solved！
