### ISSUE TITLE
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization'

### ISSUE THREAD

**Issue by gahangandi11** [cfzd/Ultra-Fast-Lane-Detection-v2#92]
I have the following error when i run this model. Can you tell me which pytorch version to use to run this model.

I have the following error

/home/nvidia/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from evaluation.eval_wrapper import eval_lane
  File "/home/nvidia/Ultra-Fast-Lane-Detection-v2/evaluation/eval_wrapper.py", line 2, in <module>
    from data.dataloader import get_test_loader
  File "/home/nvidia/Ultra-Fast-Lane-Detection-v2/data/dataloader.py", line 4, in <module>
    import torchvision.transforms as transforms
  File "/home/nvidia/.local/lib/python3.8/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/home/nvidia/.local/lib/python3.8/site-packages/torchvision/models/__init__.py", line 17, in <module>
    from . import detection, optical_flow, quantization, segmentation, video
  File "/home/nvidia/.local/lib/python3.8/site-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/home/nvidia/.local/lib/python3.8/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/home/nvidia/.local/lib/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py", line 5, in <module>
    from torch.ao.quantization import DeQuantStub, QuantStub
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/home/nvidia/.local/lib/python3.8/site-packages/torch/ao/quantization/__init__.py)

**Comment by cfzd** [comment]
https://www.google.com.hk/search?q=ImportError%3A+cannot+import+name+%27QuantStub%27+from+%27torch.ao.quantization%27&sourceid=chrome&ie=UTF-8
