### ISSUE TITLE
miss out0_normal.txt when evaluate

### ISSUE THREAD

**Issue by 1x00RicardoX** [cfzd/Ultra-Fast-Lane-Detection-v2#94]
训练好一轮之后，报如下错误：
After training for one round, the following error occurred:
```
sh: 1: ./evaluation/culane/evaluate: not found
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    res = eval_lane(net, cfg, ep = epoch, logger = logger)
  File "/root/test0305/Ultra-Fast-Lane-Detection-v2-master/evaluation/eval_wrapper.py", line 899, in eval_lane
    res = call_culane_eval(cfg.data_root, 'culane_eval_tmp', cfg.test_work_dir)
  File "/root/test0305/Ultra-Fast-Lane-Detection-v2-master/evaluation/eval_wrapper.py", line 1022, in call_culane_eval
    res_all['res_normal'] = read_helper(out0)
  File "/root/test0305/Ultra-Fast-Lane-Detection-v2-master/evaluation/eval_wrapper.py", line 960, in read_helper
    lines = open(path, 'r').readlines()[1:]
FileNotFoundError: [Errno 2] No such file or directory: '/root/tf-logs/20230306_145049_lr_5e-03_b_32/txt/out0_normal.txt'
```

完全按照 INSTALL.md 安装，其中到第五步安装完opencv，使用软连接后Option 1提示：
I installed everything according to the instructions in INSTALL.md, including installing OpenCV in step five and creating a soft link.However, Option 1 gave an error message. 
`fatal error: opencv2/core.hpp: No such file or directory`

后来选择Option 2安装完成没有报错。
I then chose Option 2 and completed the installation without any errors.

请问可能哪里出现了问题，非常感谢您的帮助！
Can you please advise what could have gone wrong? Thank you very much for your help!

**Comment by 1x00RicardoX** [comment]
发现问题了，问题关键是 evaluate 应该在 culane 文件夹下而非 evaluation 文件夹下，因此建议将 Option 2 修改成:
Problem found. The key issue is that 'evaluate' should be under the 'culane' directory instead of the 'evaluation' directory. Therefore, it is suggested to modify Option 2 as follows: 

```
cd evaluation/culane
mkdir build
cmake .
make
mv culane_evaluator ./evaluate
```
